/**
 * @file ProDefine.h
 *
 */

#ifndef PRODEFINE_H_
#define PRODEFINE_H_

/* Random Base */
#define RANDOM_BASE            10000

/* Default Slot Item Value */
#define DEFAULT_SLOT_1_CHERRY   5000
#define DEFAULT_SLOT_1_APPLE    1000
#define DEFAULT_SLOT_1_ORANGE   1000
#define DEFAULT_SLOT_1_COIN     1000
#define DEFAULT_SLOT_1_BAR       500
#define DEFAULT_SLOT_1_DIAMOND   500
#define DEFAULT_SLOT_1_CROWN     500
#define DEFAULT_SLOT_1_FREECOIN  300
#define DEFAULT_SLOT_1_ROULETTE  200

#define DEFAULT_SLOT_2_CHERRY   5000
#define DEFAULT_SLOT_2_APPLE    1000
#define DEFAULT_SLOT_2_ORANGE   1000
#define DEFAULT_SLOT_2_COIN     1000
#define DEFAULT_SLOT_2_BAR       500
#define DEFAULT_SLOT_2_DIAMOND   500
#define DEFAULT_SLOT_2_CROWN     500
#define DEFAULT_SLOT_2_FREECOIN  300
#define DEFAULT_SLOT_2_ROULETTE  200

#define DEFAULT_SLOT_3_CHERRY   5000
#define DEFAULT_SLOT_3_APPLE    1000
#define DEFAULT_SLOT_3_ORANGE   1000
#define DEFAULT_SLOT_3_COIN     1000
#define DEFAULT_SLOT_3_BAR       500
#define DEFAULT_SLOT_3_DIAMOND   500
#define DEFAULT_SLOT_3_CROWN     500
#define DEFAULT_SLOT_3_FREECOIN  300
#define DEFAULT_SLOT_3_ROULETTE  200

/* Default Match Item Value */
#define DEFAULT_MATCH_CHERRY   5000
#define DEFAULT_MATCH_APPLE    1000
#define DEFAULT_MATCH_ORANGE   1000
#define DEFAULT_MATCH_COIN     1000
#define DEFAULT_MATCH_BAR       500
#define DEFAULT_MATCH_DIAMOND   500
#define DEFAULT_MATCH_CROWN     500
#define DEFAULT_MATCH_MULTIPLE  300
#define DEFAULT_MATCH_TRAIN     200

/* Default Match Multiple Item Value */
#define DEFAULT_MATCH_MULTIPLE_CHERRY   1500
#define DEFAULT_MATCH_MULTIPLE_APPLE    1500
#define DEFAULT_MATCH_MULTIPLE_ORANGE   1500
#define DEFAULT_MATCH_MULTIPLE_COIN     1500
#define DEFAULT_MATCH_MULTIPLE_BAR      1500
#define DEFAULT_MATCH_MULTIPLE_DIAMOND  1500
#define DEFAULT_MATCH_MULTIPLE_CROWN    1000
#define DEFAULT_MATCH_MULTIPLE_MULTIPLE    0
#define DEFAULT_MATCH_MULTIPLE_TRAIN       0

#endif /* PRODEFINE_H_ */
